Style Color picker
pagarme/former-kit-skin-pagarme pull request #291
Opened 2021-09-29 18:34 UTC by LorenaKauane

## Context
Add  style Color Picker

## Checklist
- [x] Add style Color Picker

## Linked Issues
- [x] [Resolves](https://mundipagg.atlassian.net/browse/EXP-998)

2021-09-30 13:29 UTC, Hrfreire commented on src/styles/color-picker/index.css
> +
fico uma linha em branco aqui

2021-09-30 18:55 UTC, Joaovjs approved these changes

2021-09-30 18:59 UTC, Joaovjs requested changes
Acredito que faltou mudar a versão do projeto no package.json

2021-09-30 19:05 UTC, Joaovjs commented on package.json
> +  "version": "2.11.2",
acho que como foi adicionado uma feature nova (Colorpicker) a versão poderia ser 2.12.0

2021-09-30 19:19 UTC, Joaovjs approved these changes

2021-10-01 12:46 UTC, Hrfreire approved these changes

2021-10-04 16:52 UTC, merged