[EXP-1100] Adicionar style submenu de recorrência na sidebar
pagarme/former-kit-skin-pagarme pull request #300
Opened 2021-12-01 17:23 UTC by LorenaKauane

## Context
adicionar style submenu de recorrência na sidebar

## Checklist
- [x] Adicionar border na lateral do item do menu

## Linked Issues
- [x] [Resolves](https://mundipagg.atlassian.net/jira/software/c/projects/EXP/boards/185?modal=detail&selectedIssue=EXP-1100)

2021-12-03 13:48 UTC, Hrfreire approved these changes

2021-12-06 12:52 UTC, Joaovjs approved these changes

2021-12-06 12:54 UTC, gabriel949 requested changes
- [ ] Tá rolando esse erro no console
![Captura de tela de 2021-12-06 09-52-07](https://user-images.githubusercontent.com/29731690/144849422-31c2b553-5639-415d-83e0-c0ade1ccc748.png)
- [ ] as datas dos deteinputs nessa branch tá no padrão americano, mas não sei se tem haver com o seu PR
![Captura de tela de 2021-12-06 09-50-56](https://user-images.githubusercontent.com/29731690/144849559-55e9dc2d-73e0-4bbd-b708-3717ef2f052c.png)

2021-12-06 13:17 UTC, Hrfreire approved these changes

2021-12-06 13:18 UTC, Joaovjs approved these changes

2021-12-06 13:42 UTC, gabriel949 approved these changes

2021-12-06 13:53 UTC, merged