[/SEARCH - MCFIN-190] Ajustar popover do former-kit
pagarme/former-kit-skin-pagarme pull request #323
Opened 2023-06-09 15:10 UTC by jhserodio

## Context
Update style to propover component variables

## Linked Issues
- [x] Resolves #MCFIN-190
- [Figma](https://www.figma.com/file/BBQcxO1U37PwqQjwDq7Ybl/Estudo-Novo-Filtro?type=design&node-id=2016-40528&t=cQto20Y5a1lymN8L-0)
- [Task MCFIN-190](https://mundipagg.atlassian.net/jira/software/c/projects/MCFIN/boards/854?modal=detail&selectedIssue=MCFIN-190)

2023-06-12 13:14 UTC, Joaovjs approved these changes

2023-06-12 13:14 UTC, Joaovjs requested changes
Lint quebrou

2023-06-21 14:19 UTC, Joaovjs approved these changes

2023-06-22 21:16 UTC, gabriel949 approved these changes

2023-06-28 13:24 UTC, merged